COGNITO_CLIENT_ID: 1cukmlfliokbr5rjd8u4hhmcii
COGNITO_REGION: ap-southeast-1
COGNITO_USER_POOLID: ap-southeast-1_4303LikBo
MONGO_DB_NAME: authDb
RIDER_PROFILE_SERVICE_PATH: http://rider-service.perftest:8080