COGNITO_CLIENT_ID: 7n3j5nn2krhcg81q50j5jdgnij
COGNITO_REGION: ap-southeast-1
COGNITO_USER_POOLID: ap-southeast-1_EusLkGiLC
MONGO_DB_NAME: authDb
RIDER_PROFILE_SERVICE_PATH: http://rider-service.qa:8080