---
# Source: java-gradle-service-eks/templates/devops-config/application-devops-config.yml
# This file was generated at 08/12/2020 10:57:24 using generator Version: 1.0

variables:
    ## This corresponds to the central pipeline archetype. It should be same as specified in .gitlab-ci.yml. It is used to select the correspond archetype artifacts from pipeline-helper.
    APP_PIPELINE_ARCHETYPE: node-eks

    ## This is the Archetype category 
    APP_PIPELINE_ARCHETYPE_CATEGORY:  node    

    ## This is the Archetype versionm corresponding to the pipeline archetype of the service. It should be same as specified in .gitlab-ci.yml. It is used to select the correspond archetype artifacts from pipeline-helper.
    APP_ARCHETYPE_VERSION: '1.0'
    
    ## This contains the list of overrides that individual service can override. For a possible list of all configuration see below:
    ## Application overrides
    #########################################################################
    ## This is the name by which deployment in kubernetes will be created. Typically, this is the service name without special character/ spaces.
    APP_SERVICE_NAME: auth-service

    ## This is the service port on which application is running. The same is exposed in docker container.
    APP_SERVICE_PORT: 3000
    ## This is the CMDB ID of the service used to identfy uniquely. It is used to generate the unique soanr project Id.
    APP_SERVICE_ID: auth-service

    ## This is the path of pom.xml for the main module. Typically, it will be root. But for a spring multi-module project, it could be different.
    APP_MAIN_MODULE: ./
    ## This is the app health check endpoint. This is used in pipeline healthcheck stage. This response to this should be UP.
    APP_HEALTHCHECK_ENDPOINT: /
  
    APP_INGRESS_PATH: auth-service
    # APP_INGRESS_SCHEME: external

    JOB_TOGGLE_FUNCTIONAL_TEST: 0
    JOB_TOGGLE_SYSTEM_TEST: 0
    JOB_TOGGLE_PERFORMANCE_TEST: 0
    JOB_TOGGLE_DOCKER_GOSS: 0
    JOB_TOGGLE_CODE_QUALITY_CHECK: 0
    JOB_TOGGLE_NODE_TEST: 0
    JOB_TOGGLE_COVERAGE_CHECK: 0
    JOB_TOGGLE_VERSION_BUMP: 0
    JOB_TOGGLE_SECRET_SCAN: 0
    JOB_ZAP_SCAN: 0
    APP_INGRESS_ENABLED: 'true'
