DEPLOYMENT:
    ENV: dev
    NAMESPACE: dev
    CONFIG_FILES:
        - "config/auth-service.default.yaml"
        - "config/auth-service.dev.yaml"
    INGRESS:
      ENABLED: 'true'
APP:
    INGRESS:
      ENABLED: 'true'
      EXTERNAL_ENABLED: 'false'      
    COMMAND: yarn
    COMMAND_ARGS: start
    ENVIRONMENT:
      - KEY: ENV
        VALUE: dev
      - KEY: logs.Dir
        VALUE: "/apps/logs/dev/auth-service/"
